# Purpose: 2-3 OdataUtils — General-purpose PowerShell utilities.
#############################################
#
#   ODataUtils
#
# What is ODATA?
# https://msdn.microsoft.com/en-us/library/ff478141.aspx 
#
Get-Command -Module Microsoft.PowerShell.OdataUtils
$demopath = "C:\Temp\demos"
# Remove for Demo first
if((Test-Path -Path $DemoPath\ODataDemo) -eq $true)
{
    Remove-Item -Path $DemoPath\ODataDemo
}

# Demo OData Feed / Web Service
$ODataFeed = 'http://services.odata.org/v3/(S(snyobsk1hhutkb2yulwldgf1))/odata/odata.svc' 

# Show the OData XML Definition
Start-Process $ODataFeed

# Generates a module that contains cmdlets (CDXML) to manage an OData endpoint.
Export-ODataEndpointProxy -Uri $ODataFeed -OutputModule $DemoPath\ODataDemo -AllowUnsecureConnection -Force

# Look at Generated Files -
Start-Process $DemoPath\ODataDemo

# CDXML Cmdlet Definition XML - Define the CmdLets that will be AutoGenerated
Import-Module $DemoPath\ODataDemo

# List the Generated Commands (Functions)
Get-Command -Module ODataDemo

Get-Person -AllowUnsecureConnection 
Get-PersonDetail -AllowUnsecureConnection 
PSEdit $DemoPath\ODataDemo\ComplexTypeDefinitions.psm1
PSEdit $DemoPath\ODataDemo\ODataDemo.psd1

Remove-Module OdataDemo



