# Purpose: MenuGenerator — General-purpose PowerShell utilities.
<span style="color: #00008b;">function</span> <span style="color: #8a2be2;">New-ISEMenu</span> <span style="color: #000000;">{</span>
<span style="color: #006400;">########################################################################</span>
<span style="color: #006400;"># Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.9.0</span>
<span style="color: #006400;"># Generated By: Ravikanth Chaganti</span>
<span style="color: #006400;">########################################################################</span>            

<span style="color: #006400;">#region Import the Assemblies</span>
<span style="color: #008080;">[reflection.assembly]</span><span style="color: #a9a9a9;">::</span><span style="color: #000000;">loadwithpartialname</span><span style="color: #000000;">(</span><span style="color: #8b0000;">"System.Drawing"</span><span style="color: #000000;">)</span> <span style="color: #a9a9a9;">|</span> <span style="color: #0000ff;">Out-Null</span>
<span style="color: #008080;">[reflection.assembly]</span><span style="color: #a9a9a9;">::</span><span style="color: #000000;">loadwithpartialname</span><span style="color: #000000;">(</span><span style="color: #8b0000;">"System.Windows.Forms"</span><span style="color: #000000;">)</span> <span style="color: #a9a9a9;">|</span> <span style="color: #0000ff;">Out-Null</span>
<span style="color: #006400;">#endregion</span>            

<span style="color: #006400;">#region Generated Form Objects</span>
<span style="color: #ff4500;">$form1</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Windows.Forms.Form</span>
<span style="color: #ff4500;">$checkBox1</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Windows.Forms.CheckBox</span>
<span style="color: #ff4500;">$button2</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Windows.Forms.Button</span>
<span style="color: #ff4500;">$button1</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Windows.Forms.Button</span>
<span style="color: #ff4500;">$textBox3</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Windows.Forms.TextBox</span>
<span style="color: #ff4500;">$label3</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Windows.Forms.Label</span>
<span style="color: #ff4500;">$textBox2</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Windows.Forms.TextBox</span>
<span style="color: #ff4500;">$label2</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Windows.Forms.Label</span>
<span style="color: #ff4500;">$textBox1</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Windows.Forms.TextBox</span>
<span style="color: #ff4500;">$label1</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Windows.Forms.Label</span>
<span style="color: #ff4500;">$InitialFormWindowState</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Windows.Forms.FormWindowState</span>
<span style="color: #006400;">#endregion Generated Form Objects</span>            

<span style="color: #006400;">#----------------------------------------------</span>
<span style="color: #006400;">#Generated Event Script Blocks</span>
<span style="color: #006400;">#----------------------------------------------</span>
<span style="color: #ff4500;">$button1_OnClick</span><span style="color: #a9a9a9;">=</span>
<span style="color: #000000;">{</span>
    <span style="color: #00008b;">if</span> <span style="color: #000000;">(</span><span style="color: #ff4500;">$textBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Text</span><span style="color: #000000;">)</span> <span style="color: #000000;">{</span>
        <span style="color: #ff4500;">$addonName</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$textBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Text</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">ToString</span><span style="color: #000000;">(</span><span style="color: #000000;">)</span>
    <span style="color: #000000;">}</span> <span style="color: #00008b;">else</span> <span style="color: #000000;">{</span>
        <span style="color: #008080;">[System.Windows.Forms.MessageBox]</span><span style="color: #a9a9a9;">::</span><span style="color: #000000;">Show</span><span style="color: #000000;">(</span><span style="color: #8b0000;">"You must supply all parameters"</span><span style="color: #000000;">)</span>
        <span style="color: #00008b;">return</span>
    <span style="color: #000000;">}</span>
    <span style="color: #00008b;">if</span> <span style="color: #000000;">(</span><span style="color: #ff4500;">$textBox2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Text</span><span style="color: #000000;">)</span> <span style="color: #000000;">{</span>
        <span style="color: #ff4500;">$addonShortCut</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$textBox2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Text</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">ToString</span><span style="color: #000000;">(</span><span style="color: #000000;">)</span>
    <span style="color: #000000;">}</span> <span style="color: #00008b;">else</span> <span style="color: #000000;">{</span>
        <span style="color: #ff4500;">$addonShortCut</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">""</span>
        <span style="color: #00008b;">return</span>
    <span style="color: #000000;">}</span>
    <span style="color: #00008b;">if</span> <span style="color: #000000;">(</span><span style="color: #ff4500;">$textbox3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Text</span><span style="color: #000000;">)</span> <span style="color: #000000;">{</span>
        <span style="color: #ff4500;">$scriptBlock</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$ExecutionContext</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">InvokeCommand</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">NewScriptBlock</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$textBox3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Text</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">ToString</span><span style="color: #000000;">(</span><span style="color: #000000;">)</span><span style="color: #000000;">)</span>
    <span style="color: #000000;">}</span> <span style="color: #00008b;">else</span> <span style="color: #000000;">{</span>
        <span style="color: #008080;">[System.Windows.Forms.MessageBox]</span><span style="color: #a9a9a9;">::</span><span style="color: #000000;">Show</span><span style="color: #000000;">(</span><span style="color: #8b0000;">"You must supply all parameters"</span><span style="color: #000000;">)</span>
        <span style="color: #00008b;">return</span>
    <span style="color: #000000;">}</span>
    <span style="color: #ff4500;">$menuItems</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$psise</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">CurrentPowerShellTab</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">AddOnsMenu</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Submenus</span> <span style="color: #a9a9a9;">|</span> <span style="color: #0000ff;">Select</span> <span style="color: #000080;">-ExpandProperty</span> <span style="color: #8a2be2;">DisplayName</span>
    <span style="color: #00008b;">if</span> <span style="color: #000000;">(</span><span style="color: #ff4500;">$menuItems</span> <span style="color: #a9a9a9;">-Contains</span> <span style="color: #ff4500;">$addonName</span><span style="color: #000000;">)</span> <span style="color: #000000;">{</span>
        <span style="color: #008080;">[System.Windows.Forms.MessageBox]</span><span style="color: #a9a9a9;">::</span><span style="color: #000000;">Show</span><span style="color: #000000;">(</span><span style="color: #8b0000;">"Select another Name"</span><span style="color: #000000;">)</span>
        <span style="color: #00008b;">return</span>
    <span style="color: #000000;">}</span>            

    <span style="color: #00008b;">try</span> <span style="color: #000000;">{</span>
        <span style="color: #ff4500;">$psISE</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">CurrentPowerShellTab</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">AddOnsMenu</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">SubMenus</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Add</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$addonName</span><span style="color: #a9a9a9;">,</span><span style="color: #ff4500;">$ScriptBlock</span><span style="color: #a9a9a9;">,</span><span style="color: #ff4500;">$addonShortCut</span><span style="color: #000000;">)</span> <span style="color: #a9a9a9;">|</span> <span style="color: #0000ff;">Out-Null</span>
    <span style="color: #000000;">}</span>
    <span style="color: #00008b;">catch</span> <span style="color: #000000;">{</span>
        <span style="color: #0000ff;">Write-Error</span> <span style="color: #ff4500;">$_</span>
        <span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Close</span><span style="color: #000000;">(</span><span style="color: #000000;">)</span>
        <span style="color: #00008b;">return</span>
    <span style="color: #000000;">}</span>            

    <span style="color: #00008b;">if</span> <span style="color: #000000;">(</span><span style="color: #ff4500;">$checkBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Checked</span><span style="color: #000000;">)</span> <span style="color: #000000;">{</span>
        <span style="color: #ff4500;">$profileText</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"`n`#Added by ISE Menu Creator Addon
if (`$psISE) {
`$psISE.CurrentPowerShellTab.AddOnsMenu.SubMenus.Add(`"$addonName`",`{$ScriptBlock`},`"$addonShortCut`") | Out-Null
}
"</span>
<span style="color: #0000ff;">Add-Content</span> <span style="color: #000080;">-Path</span> <span style="color: #ff4500;">$profile</span> <span style="color: #000080;">-Value</span> <span style="color: #ff4500;">$profileText</span>
    <span style="color: #000000;">}</span>            

    <span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Close</span><span style="color: #000000;">(</span><span style="color: #000000;">)</span>
<span style="color: #000000;">}</span>
<span style="color: #ff4500;">$OnLoadForm_StateCorrection</span><span style="color: #a9a9a9;">=</span>
<span style="color: #000000;">{</span><span style="color: #006400;">#Correct the initial state of the form to prevent the .Net maximized form issue</span>
 <span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">WindowState</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$InitialFormWindowState</span>
<span style="color: #000000;">}</span>            

<span style="color: #006400;">#----------------------------------------------</span>
<span style="color: #006400;">#region Generated Form Code</span>
<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">CancelButton</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$button2</span>
<span style="color: #ff4500;">$System_Drawing_Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Size</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Height</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">201</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Width</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">458</span>
<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">ClientSize</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Size</span>
<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">ControlBox</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$False</span>
<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DataBindings</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DefaultDataSourceUpdateMode</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">0</span>
<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">MaximizeBox</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$False</span>
<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">MinimizeBox</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$False</span>
<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Name</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"form1"</span>
<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">ShowIcon</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$False</span>
<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">ShowInTaskbar</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$False</span>
<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Text</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"ISE Menu Creator"</span>
<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">TopMost</span><span style="color: #a9a9a9;">=</span><span style="color: #ff4500;">$true</span>            

<span style="color: #ff4500;">$checkBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DataBindings</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DefaultDataSourceUpdateMode</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">0</span>            

<span style="color: #ff4500;">$System_Drawing_Point</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Point</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">X</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">12</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Y</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">136</span>
<span style="color: #ff4500;">$checkBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Location</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Point</span>
<span style="color: #ff4500;">$checkBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Name</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"checkBox1"</span>
<span style="color: #ff4500;">$System_Drawing_Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Size</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Height</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">24</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Width</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">181</span>
<span style="color: #ff4500;">$checkBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Size</span>
<span style="color: #ff4500;">$checkBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">TabIndex</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">6</span>
<span style="color: #ff4500;">$checkBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Text</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"Add to ISE Profile Script"</span>
<span style="color: #ff4500;">$checkBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">UseVisualStyleBackColor</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$True</span>            

<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Controls</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Add</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$checkBox1</span><span style="color: #000000;">)</span>            

<span style="color: #ff4500;">$button2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DataBindings</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DefaultDataSourceUpdateMode</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">0</span>
<span style="color: #ff4500;">$button2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DialogResult</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">2</span>            

<span style="color: #ff4500;">$System_Drawing_Point</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Point</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">X</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">301</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Y</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">166</span>
<span style="color: #ff4500;">$button2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Location</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Point</span>
<span style="color: #ff4500;">$button2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Name</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"button2"</span>
<span style="color: #ff4500;">$System_Drawing_Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Size</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Height</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">23</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Width</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">75</span>
<span style="color: #ff4500;">$button2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Size</span>
<span style="color: #ff4500;">$button2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">TabIndex</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">8</span>
<span style="color: #ff4500;">$button2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Text</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"Cancel"</span>
<span style="color: #ff4500;">$button2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">UseVisualStyleBackColor</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$True</span>
<span style="color: #ff4500;">$button2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">add_Click</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$button2_OnClick</span><span style="color: #000000;">)</span>            

<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Controls</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Add</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$button2</span><span style="color: #000000;">)</span>            

<span style="color: #ff4500;">$button1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DataBindings</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DefaultDataSourceUpdateMode</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">0</span>            

<span style="color: #ff4500;">$System_Drawing_Point</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Point</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">X</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">76</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Y</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">166</span>
<span style="color: #ff4500;">$button1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Location</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Point</span>
<span style="color: #ff4500;">$button1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Name</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"button1"</span>
<span style="color: #ff4500;">$System_Drawing_Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Size</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Height</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">23</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Width</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">75</span>
<span style="color: #ff4500;">$button1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Size</span>
<span style="color: #ff4500;">$button1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">TabIndex</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">7</span>
<span style="color: #ff4500;">$button1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Text</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"Save"</span>
<span style="color: #ff4500;">$button1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">UseVisualStyleBackColor</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$True</span>
<span style="color: #ff4500;">$button1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">add_Click</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$button1_OnClick</span><span style="color: #000000;">)</span>            

<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Controls</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Add</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$button1</span><span style="color: #000000;">)</span>            

<span style="color: #ff4500;">$textBox3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">AcceptsReturn</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$True</span>
<span style="color: #ff4500;">$textBox3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DataBindings</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DefaultDataSourceUpdateMode</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">0</span>
<span style="color: #ff4500;">$System_Drawing_Point</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Point</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">X</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">127</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Y</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">61</span>
<span style="color: #ff4500;">$textBox3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Location</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Point</span>
<span style="color: #ff4500;">$textBox3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Multiline</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$True</span>
<span style="color: #ff4500;">$textBox3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Name</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"textBox3"</span>
<span style="color: #ff4500;">$System_Drawing_Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Size</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Height</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">66</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Width</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">304</span>
<span style="color: #ff4500;">$textBox3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Size</span>
<span style="color: #ff4500;">$textBox3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">TabIndex</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">5</span>
<span style="color: #ff4500;">$textBox3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">AcceptsTab</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$True</span>            

<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Controls</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Add</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$textBox3</span><span style="color: #000000;">)</span>            

<span style="color: #ff4500;">$label3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DataBindings</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DefaultDataSourceUpdateMode</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">0</span>            

<span style="color: #ff4500;">$System_Drawing_Point</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Point</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">X</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">12</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Y</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">64</span>
<span style="color: #ff4500;">$label3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Location</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Point</span>
<span style="color: #ff4500;">$label3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Name</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"label3"</span>
<span style="color: #ff4500;">$System_Drawing_Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Size</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Height</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">23</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Width</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">100</span>
<span style="color: #ff4500;">$label3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Size</span>
<span style="color: #ff4500;">$label3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">TabIndex</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">4</span>
<span style="color: #ff4500;">$label3</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Text</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"Script Block"</span>            

<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Controls</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Add</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$label3</span><span style="color: #000000;">)</span>            

<span style="color: #ff4500;">$textBox2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DataBindings</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DefaultDataSourceUpdateMode</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">0</span>
<span style="color: #ff4500;">$System_Drawing_Point</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Point</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">X</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">127</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Y</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">35</span>
<span style="color: #ff4500;">$textBox2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Location</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Point</span>
<span style="color: #ff4500;">$textBox2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Name</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"textBox2"</span>
<span style="color: #ff4500;">$System_Drawing_Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Size</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Height</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">20</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Width</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">181</span>
<span style="color: #ff4500;">$textBox2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Size</span>
<span style="color: #ff4500;">$textBox2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">TabIndex</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">3</span>            

<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Controls</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Add</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$textBox2</span><span style="color: #000000;">)</span>            

<span style="color: #ff4500;">$label2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DataBindings</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DefaultDataSourceUpdateMode</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">0</span>            

<span style="color: #ff4500;">$System_Drawing_Point</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Point</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">X</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">12</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Y</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">38</span>
<span style="color: #ff4500;">$label2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Location</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Point</span>
<span style="color: #ff4500;">$label2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Name</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"label2"</span>
<span style="color: #ff4500;">$System_Drawing_Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Size</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Height</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">23</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Width</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">100</span>
<span style="color: #ff4500;">$label2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Size</span>
<span style="color: #ff4500;">$label2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">TabIndex</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">2</span>
<span style="color: #ff4500;">$label2</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Text</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"Shortcut Key"</span>            

<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Controls</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Add</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$label2</span><span style="color: #000000;">)</span>            

<span style="color: #ff4500;">$textBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DataBindings</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DefaultDataSourceUpdateMode</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">0</span>
<span style="color: #ff4500;">$System_Drawing_Point</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Point</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">X</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">127</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Y</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">6</span>
<span style="color: #ff4500;">$textBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Location</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Point</span>
<span style="color: #ff4500;">$textBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Name</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"textBox1"</span>
<span style="color: #ff4500;">$System_Drawing_Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Size</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Height</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">20</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Width</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">181</span>
<span style="color: #ff4500;">$textBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Size</span>
<span style="color: #ff4500;">$textBox1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">TabIndex</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">1</span>            

<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Controls</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Add</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$textBox1</span><span style="color: #000000;">)</span>            

<span style="color: #ff4500;">$label1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DataBindings</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">DefaultDataSourceUpdateMode</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">0</span>            

<span style="color: #ff4500;">$System_Drawing_Point</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Point</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">X</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">12</span>
<span style="color: #ff4500;">$System_Drawing_Point</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Y</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">9</span>
<span style="color: #ff4500;">$label1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Location</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Point</span>
<span style="color: #ff4500;">$label1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Name</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"label1"</span>
<span style="color: #ff4500;">$System_Drawing_Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #0000ff;">New-Object</span> <span style="color: #8a2be2;">System.Drawing.Size</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Height</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">23</span>
<span style="color: #ff4500;">$System_Drawing_Size</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Width</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">100</span>
<span style="color: #ff4500;">$label1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Size</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$System_Drawing_Size</span>
<span style="color: #ff4500;">$label1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">TabIndex</span> <span style="color: #a9a9a9;">=</span> <span style="color: #800080;">0</span>
<span style="color: #ff4500;">$label1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Text</span> <span style="color: #a9a9a9;">=</span> <span style="color: #8b0000;">"Addon Menu Name"</span>            

<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Controls</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">Add</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$label1</span><span style="color: #000000;">)</span>            

<span style="color: #006400;">#endregion Generated Form Code</span>            

<span style="color: #006400;">#Save the initial state of the form</span>
<span style="color: #ff4500;">$InitialFormWindowState</span> <span style="color: #a9a9a9;">=</span> <span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">WindowState</span>
<span style="color: #006400;">#Init the OnLoad event to correct the initial state of the form</span>
<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">add_Load</span><span style="color: #000000;">(</span><span style="color: #ff4500;">$OnLoadForm_StateCorrection</span><span style="color: #000000;">)</span>
<span style="color: #006400;">#Show the Form</span>
<span style="color: #ff4500;">$form1</span><span style="color: #a9a9a9;">.</span><span style="color: #000000;">ShowDialog</span><span style="color: #000000;">(</span><span style="color: #000000;">)</span><span style="color: #a9a9a9;">|</span> <span style="color: #0000ff;">Out-Null</span>            

<span style="color: #000000;">}</span> <span style="color: #006400;">#End Function</span>