# Purpose: Primaryemail — General-purpose PowerShell utilities.
# Primaryemail.ps1
$file = "c:\uninstall\allcomps.TXT"

$smtpServer = "96.131.116.237"

$msg = new-object Net.Mail.MailMessage
$att = new-object Net.Mail.Attachment($file)
$smtp = new-object Net.Mail.SmtpClient($smtpServer)

$msg.From = "PowerShell2@example.com"
$msg.To.Add("nteam@example.com")
# $msg.To.Add("kkreitin@example.com")
$msg.Subject = "Powershell Test Mail Generated by Kerry"
$msg.Body = "Powershell2 EMAIL - DO NOT REPLY TO THIS EMAIL"
# $msg.Body = "DO NOT REPLY TO THIS EMAIL"
$msg.Attachments.Add($att)

$smtp.Send($msg)

$att.Dispose()